"""Command input, STT, LLM parser, and TTS defaults."""

DEFAULT_ENABLE_MICROPHONE = False
DEFAULT_STT_LANGUAGE = "ko-KR"
DEFAULT_STT_DEVICE_INDEX = -1
DEFAULT_STT_ENERGY_THRESHOLD = 300.0
DEFAULT_STT_PAUSE_THRESHOLD = 0.45
DEFAULT_STT_PHRASE_THRESHOLD = 0.15
DEFAULT_STT_NON_SPEAKING_DURATION_SEC = 0.25
DEFAULT_STT_PHRASE_TIME_LIMIT_SEC = 3.0
DEFAULT_STT_DYNAMIC_ENERGY = True
DEFAULT_STT_AMBIENT_DURATION_SEC = 0.5

DEFAULT_OLLAMA_URL = "http://localhost:11434/api/generate"
DEFAULT_LLM_MODEL = "gemma3:1b"
DEFAULT_LLM_TIMEOUT_SEC = 25.0
DEFAULT_COMMAND_MIN_CONFIDENCE = 0.55
DEFAULT_USE_LOCAL_PARSER = True
DEFAULT_USE_LLM_FALLBACK = True
DEFAULT_PARSER_MODE = "llm_primary"

DEFAULT_ENABLE_TTS = True
DEFAULT_TTS_ENGINE = "auto"
DEFAULT_TTS_VOICE = "ko-KR-InJoonNeural"
DEFAULT_TTS_RATE = 165
DEFAULT_TTS_EDGE_RATE = "+5%"
DEFAULT_TTS_PITCH = "-8Hz"
DEFAULT_TTS_TIMEOUT_SEC = 20.0

TTS_SERVICE_DEFAULT_ENABLED = False
TTS_SERVICE_DEFAULT_VOICE = "ko"
TTS_SERVICE_DEFAULT_EDGE_RATE = "+5%"
TTS_SERVICE_DEFAULT_PITCH = "-8Hz"
TTS_SERVICE_DEFAULT_TIMEOUT_SEC = 8.0
