"""Gripper grasp verification constants."""

GRASP_VERIFY_TIMEOUT_SEC = 3.0
GRASP_VERIFY_POLL_SEC = 0.2
GRASP_VERIFY_STABLE_COUNT = 3
GRASP_RETRY_LIMIT = 5
GRASP_RETRY_WAIT_SEC = 0.5
GRASP_ADVANCE_DISTANCE_M = 0.20
GRIPPER_CLOSED_WIDTH_THRESHOLD_MM = 12.0
GRIPPER_EMPTY_CLOSED_WIDTH_THRESHOLD_MM = 12.0
PREGRASP_MEASUREMENT_SETTLE_TIMEOUT_SEC = 3.0
PREGRASP_MAX_EXTRA_DESCENT_M = 0.03

DROP_MONITOR_GRACE_SEC = 0.5
DROP_MONITOR_POLL_SEC = 0.2
DROP_MONITOR_STABLE_COUNT = 3
DROP_MONITOR_STOP_TIMEOUT_SEC = 1.0
DROP_MONITOR_WIDTH_RELEASE_DELTA_MM = 5.0
