"""Gripper grasp verification constants."""

GRASP_VERIFY_TIMEOUT_SEC = 3.0
GRASP_VERIFY_POLL_SEC = 0.2
GRASP_VERIFY_STABLE_COUNT = 3
GRASP_RETRY_LIMIT = 5
GRASP_ADVANCE_DISTANCE_M = 0.20
GRIPPER_CLOSED_WIDTH_THRESHOLD_MM = 5.0
