"""Human handoff search and movement constants."""

HANDOVER_SEARCH_TIMEOUT_SEC = 45.0
OBSERVATION_TIMEOUT_SEC = 20.0

HAND_POSE_WAIT_AFTER_DETECTION_SEC = 1.0
HAND_POSE_STABLE_TOLERANCE_M = 0.03

ALLOW_SEARCH_VERTEX_FALLBACK_FOR_HANDOVER = False

HANDOVER_HAND_X_OFFSET_M = -0.00
HANDOVER_HAND_Z_OFFSET_M = 0.08

HANDOVER_REPLAN_MAX_ATTEMPTS = 10
HANDOVER_REPLAN_X_STEP_M = 0.03
