"""Human handoff search and movement constants."""

HANDOVER_SEARCH_TIMEOUT_SEC = 45.0
OBSERVATION_TIMEOUT_SEC = 20.0
HANDOVER_SEARCH_EXECUTOR_MAX_WORKERS = 2
HANDOVER_OBSERVATION_MIN_SLEEP_SEC = 0.01
HANDOVER_OBSERVATION_MAX_SLEEP_SEC = 0.1
HANDOVER_OBSERVATION_LOG_INTERVAL_SEC = 0.7

HAND_POSE_WAIT_AFTER_DETECTION_SEC = 1.0
HAND_POSE_STABLE_TOLERANCE_M = 0.03

ALLOW_SEARCH_VERTEX_FALLBACK_FOR_HANDOVER = False

HANDOVER_HAND_X_OFFSET_M = -0.00
HANDOVER_HAND_Z_OFFSET_M = 0.10
HANDOVER_TARGET_MIN_Z_CLEARANCE_M = 0.10

HANDOVER_REPLAN_MAX_ATTEMPTS = 0
HANDOVER_REPLAN_X_STEP_M = 0.03

HANDOFF_WAIT_POLL_SEC = 0.1
HANDOFF_RELEASE_WAIT_SEC = 0.8
