"""Pick target planning constants."""

SAFE_Z = 0.40
PICK_TRAVEL_Z_CLEARANCE_M = 0.10
APPROACH_Z_OFFSET = 0.18
GRASP_Z_OFFSET = 0.03
OBJECT_Z_HEIGHT_BIAS_M = 0.03
OBSERVE_X_OFFSET_M = 0.08
PICK_GRASP_YAW_OFFSET_DEG = -180.0
