"""Return workflow force-descent constants."""

RETURN_HOME_DESCENT_STEP_M = 0.01
RETURN_HOME_FORCE_THRESHOLD_N = 8.0
RETURN_FLOOR_MAX_BASE_Z_M = 0.07
RETURN_HAND_CLOSE_ROI_CENTER_X = 0.70
RETURN_HAND_CLOSE_ROI_CENTER_Y = 0.60
RETURN_HAND_CLOSE_ROI_WIDTH_RATIO = 0.35
RETURN_HAND_CLOSE_ROI_HEIGHT_RATIO = 0.70
RETURN_HAND_CLOSE_ROI_TIMEOUT_SEC = 5.0
RETURN_HAND_CLOSE_DEPTH_MIN_MM = 140.0
RETURN_HAND_CLOSE_DEPTH_MAX_MM = 180.0
