"""Return workflow force-descent constants."""

RETURN_HOME_DESCENT_STEP_M = 0.01
RETURN_HOME_FORCE_THRESHOLD_N = 8.0
RETURN_HAND_CLOSE_ROI_CENTER_X = 0.70
RETURN_HAND_CLOSE_ROI_CENTER_Y = 0.50
RETURN_HAND_CLOSE_ROI_WIDTH_RATIO = 0.35
RETURN_HAND_CLOSE_ROI_HEIGHT_RATIO = 1.0
RETURN_HAND_CLOSE_ROI_TIMEOUT_SEC = 5.0
RETURN_HAND_CLOSE_ROI_POLL_SEC = 0.1
RETURN_HAND_CLOSE_DEPTH_MIN_MM = 160.0
RETURN_HAND_CLOSE_DEPTH_MAX_MM = 280.0
RETURN_TOOL_RELEASE_WAIT_SEC = 0.8
RETURN_DRAWER_PLACE_WRIST_YAW_DEG = -140.0
RETURN_DRAWER_PLACE_RECOVERY_EXTRA_YAW_DEG = 180.0
RETURN_PREPARE_GRIPPER_OPEN_WAIT_SEC = 0.5
