"""Debug and OpenCV UI constants."""

ROBOT_WINDOW_NAME = "YOLO Robot Pick"
HAND_GRASP_WINDOW_NAME = "Hand Grasp Detection"

UI_CONNECTION_CHECK_PERIOD_SEC = 1.0
UI_CAMERA_TIMEOUT_SEC = 3.0
UI_DETECTOR_TIMEOUT_SEC = 3.0
UI_ROBOT_NODE_NAMES = "macgyvbot_main_node,macgyvbot"
DISPLAY_DEBUG_WINDOWS_DEFAULT = False
