"""VLM grasp point selection constants."""

GRASP_POINT_MODE_CENTER = "center"
GRASP_POINT_MODE_VLM = "vlm"
GRASP_POINT_MODE_VLM_ONLY_QWEN3B = "vlm_only_qwen3b"
GRASP_POINT_MODE_VLM_ONLY_QWEN7B = "vlm_only_qwen7b"
GRASP_POINT_MODE_VLM_ONLY_SMOL = "vlm_only_smol"
GRASP_POINT_MODE_API = "api"
DEFAULT_GRASP_POINT_MODE = GRASP_POINT_MODE_VLM_ONLY_QWEN3B

VLM_INFERENCE_HISTORY_ENABLED = True
VLM_INFERENCE_HISTORY_DIR = "src/macgyvbot_perception/data/inference_history"
VLM_DATA_ROOT = "src/macgyvbot_perception/data"
VLM_YAW_PCA_DEBUG_DIR = "src/macgyvbot_perception/data/yaw_pca"

VLM_GRASP_GRID_SIZES = ((3, 3), (4, 4))
VLM_DEFAULT_MAX_IMAGE_SIZE = 640
VLM_DEFAULT_MAX_NEW_TOKENS = 96
VLM_DEFAULT_USE_4BIT = True

VLM_MODEL_SMOL = "HuggingFaceTB__SmolVLM2-2.2B-Instruct"
VLM_MODEL_QWEN3B = "Qwen/Qwen2.5-VL-3B-Instruct"
VLM_MODEL_QWEN7B = "Qwen/Qwen2.5-VL-7B-Instruct"

GRASP_POINT_API_MODEL = "gemini-2.5-flash"
GRASP_POINT_API_BASE_URL = "https://generativelanguage.googleapis.com/v1beta"
GRASP_POINT_API_ENV_FILENAME = ".env"
GRASP_POINT_API_KEY_NAME = "GEMINI_API_KEY"
GRASP_POINT_API_MAX_IMAGE_SIZE = 640
GRASP_POINT_API_MAX_OUTPUT_TOKENS = 256
GRASP_POINT_API_TIMEOUT_SEC = 30.0
GRASP_POINT_API_TEMPERATURE = 0.0
GRASP_POINT_API_THINKING_BUDGET = 0

VLM_ONLY_MODEL_BY_MODE = {
    GRASP_POINT_MODE_VLM_ONLY_SMOL: VLM_MODEL_SMOL,
    GRASP_POINT_MODE_VLM_ONLY_QWEN3B: VLM_MODEL_QWEN3B,
    GRASP_POINT_MODE_VLM_ONLY_QWEN7B: VLM_MODEL_QWEN7B,
}

VLM_ONLY_MODES = tuple(VLM_ONLY_MODEL_BY_MODE.keys())

VLM_GRASP_SERVICE_NAME = "/vlm_grasp"
VLM_SERVICE_WAIT_TIMEOUT_SEC = 2.0
VLM_SERVICE_RESPONSE_TIMEOUT_SEC = 30.0

SAM_YAW_SERVICE_NAME = "/sam_yaw"
SAM_YAW_SERVICE_WAIT_TIMEOUT_SEC = 2.0
SAM_YAW_SERVICE_RESPONSE_TIMEOUT_SEC = 5.0

SAM_ENABLED_DEFAULT = True
SAM_BACKEND_DEFAULT = "mobile_sam"
SAM_MODEL_TYPE_DEFAULT = "vit_t"
SAM_DEVICE_DEFAULT = "cuda"
VLM_DEVICE_CUDA = "cuda"
VLM_DEVICE_CPU = "cpu"
VLM_DEVICE_MAP_AUTO = "auto"
SAM_DEPTH_TOLERANCE_MM = 30.0
SAM_DEPTH_MIN_VALID_RATIO = 0.03
SAM_DEPTH_EXPAND_ITERATIONS = 1
