"""VLM grasp point selection constants."""

GRASP_POINT_MODE_CENTER = "center"
GRASP_POINT_MODE_VLM = "vlm"
GRASP_POINT_MODE_VLM_ONLY_QWEN3B = "vlm_only_qwen3b"
GRASP_POINT_MODE_VLM_ONLY_QWEN7B = "vlm_only_qwen7b"
GRASP_POINT_MODE_VLM_ONLY_SMOL = "vlm_only_smol"
GRASP_POINT_MODE_API = "api"
DEFAULT_GRASP_POINT_MODE = GRASP_POINT_MODE_VLM_ONLY_QWEN3B

VLM_INFERENCE_HISTORY_ENABLED = True
VLM_INFERENCE_HISTORY_DIR = "src/macgyvbot_perception/data/inference_history"

VLM_GRASP_GRID_SIZES = ((3, 3), (4, 4))

VLM_MODEL_SMOL = "HuggingFaceTB__SmolVLM2-2.2B-Instruct"
VLM_MODEL_QWEN3B = "Qwen/Qwen2.5-VL-3B-Instruct"
VLM_MODEL_QWEN7B = "Qwen/Qwen2.5-VL-7B-Instruct"

VLM_ONLY_MODEL_BY_MODE = {
    GRASP_POINT_MODE_VLM_ONLY_SMOL: VLM_MODEL_SMOL,
    GRASP_POINT_MODE_VLM_ONLY_QWEN3B: VLM_MODEL_QWEN3B,
    GRASP_POINT_MODE_VLM_ONLY_QWEN7B: VLM_MODEL_QWEN7B,
}

VLM_ONLY_MODES = tuple(VLM_ONLY_MODEL_BY_MODE.keys())
