"""VLM grasp point selection constants."""

GRASP_POINT_MODE_CENTER = "center"
GRASP_POINT_MODE_VLM = "vlm"
GRASP_POINT_MODE_VLM_ONLY = "vlm_only"
GRASP_POINT_MODE_API = "api"
DEFAULT_GRASP_POINT_MODE = GRASP_POINT_MODE_VLM_ONLY

VLM_GRASP_GRID_SIZES = ((3, 3), (4, 4))
